---
name: default
type: docker
kind: pipeline


steps:
  - name: test
    image: python
    commands:
      - pip install poetry
      - poetry install -v
      - poetry run mypy rplugin/python3
      - poetry run pylint rplugin/python3/copyrighter.py
